[theme]

# Primary accent for interactive elements
primaryColor = '#7409ef'

# Background color for the main content area
backgroundColor = '#6C757D'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ADB5BD'

# Color used for almost all text
textColor = '#212529'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
